### ISSUE TITLE
create-react-app example failed to compile

### ISSUE THREAD

**Issue by ephor** [expo/web-examples#11]
After 
`expo start --web`

Get
```
Failed to compile

multi /Users/****/.asdf/installs/nodejs/10.9.0/.npm/lib/node_modules/expo-cli/node_modules/react-dev-utils/webpackHotDevClient.js /Users/****/workspace/myProject/index
Module not found: Can't resolve '/Users/****/workspace/myProject/index' in '/Users/****/.asdf/installs/nodejs/10.9.0/.npm/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack'
```

**Comment by charlie632** [comment]
I have the same problem. Tried to move de index.js outside the `src` folder and updating all the imports, and I get this error:

![image](https://user-images.githubusercontent.com/8704336/54954339-08f73300-4f10-11e9-88e8-f1f33f720229.png)

**Comment by charlie632** [comment]
I have the same problem. Tried to move de index.js outside the src folder and updating all the imports, and I get this error:
![image](https://user-images.githubusercontent.com/8704336/54954414-3cd25880-4f10-11e9-89fc-7f9c0ae2685e.png)

**Comment by EvanBacon** [comment]
Thanks for the report. Please ensure your expo-cli version is up-to-date with `npm i -g expo-cli`.

**Comment by horacioh** [comment]
I tried the example and also failed. then I update `expo-cli` and changed my npm version and it worked. here's the result on my machine of `expo diagnostics`:

```shell
Expo CLI 2.14.0 environment info:
    System:
      OS: macOS High Sierra 10.13.6
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.1 - ~/.nvm/versions/node/v10.14.1/bin/node
      Yarn: 1.12.3 - ~/.nvm/versions/node/v10.14.1/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v10.14.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    IDEs:
      Android Studio: 3.0 AI-171.4443003
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.4
      react-native: ^0.59.1 => 0.59.1
    npmGlobalPackages:
      expo-cli: 2.14.0
```

hope this helps!
cc @EvanBacon @charlie632 @ephor

**Comment by EvanBacon** [comment]
I did the following which works:
* `rm -rf node_modules`
* `npm i -g expo-cli`
* `expo start --web`

```
Expo CLI 2.14.0 environment info:
    System:
      OS: macOS 10.14
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.10.0 - ~/.nvm/versions/node/v8.10.0/bin/node
      Yarn: 1.12.3 - ~/.yarn/bin/yarn
      npm: 6.5.0 - ~/.nvm/versions/node/v8.10.0/bin/npm
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.8.4 => 16.8.4 
      react-native: ^0.59.1 => 0.59.1 
    npmGlobalPackages:
      expo-cli: 2.14.0
```

I also ran:
* `nvm use 10.14.1; yarn upgrade; npm i -g expo-cli; expo start --web`

Which works as well.

<img width="1552" alt="Screen Shot 2019-04-13 at 1 16 09 AM" src="https://user-images.githubusercontent.com/9664363/56076784-bcbe4680-5d89-11e9-8c9f-f7c624ea2df1.png">
