### ISSUE TITLE
Just won't compile for web

### ISSUE THREAD

**Issue by raffjones** [expo/web-examples#13]
I followed the instructions to the letter, but end up with a vast number of unmet peer dependencies

Even after installing these manually, when I run `expo start --web --non-interactive`, the whole thing crashes out with:

    ERROR in /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/AppleTV/TVEventHandler.js
    Module not found: Error: Can't resolve '../../Utilities/Platform' in '/Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/AppleTV'
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/AppleTV/TVEventHandler.js 1:28-63
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/Touchable/Touchable.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native-gesture-handler/GestureHandler.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native-gesture-handler/index.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/@react-navigation/native/dist/Scrollables.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/@react-navigation/native/dist/index.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-navigation/src/react-navigation.js
     @ /Library/WebServer/Documents/base/expo-web-test/navigation/AppNavigator.js
     @ /Library/WebServer/Documents/base/expo-web-test/App.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/expo/AppEntry.js
     @ multi /Users/stevejones/.nvm/versions/node/v10.9.0/lib/node_modules/expo-cli/node_modules/react-dev-utils/webpackHotDevClient.js /Library/WebServer/Documents/base/expo-web-test/node_modules/expo/AppEntry.js

    ERROR in /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js
    Module not found: Error: Can't resolve '../../Utilities/Platform' in '/Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/TextInput'
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Components/TextInput/TextInputState.js 1:28-63
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Renderer/shims/ReactNative.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native/Libraries/Animated/src/AnimatedEvent.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native-gesture-handler/Swipeable.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-native-gesture-handler/index.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/@react-navigation/native/dist/Scrollables.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/@react-navigation/native/dist/index.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/react-navigation/src/react-navigation.js
     @ /Library/WebServer/Documents/base/expo-web-test/navigation/AppNavigator.js
     @ /Library/WebServer/Documents/base/expo-web-test/App.js
     @ /Library/WebServer/Documents/base/expo-web-test/node_modules/expo/AppEntry.js
     @ multi /Users/stevejones/.nvm/versions/node/v10.9.0/lib/node_modules/expo-cli/node_modules/react-dev-utils/webpackHotDevClient.js /Library/WebServer/Documents/base/expo-web-test/node_modules/expo/AppEntry.js

And a huge trace of other errors of components that cannot be found.

**Comment by tibudiyanto** [comment]
Try removing anything imported from ` @expo/samples` package.

**Comment by EvanBacon** [comment]
This is because you are using an older version of react-navigation that isn't compatible with web. Use `yarn add react-navigation@3.5.1` https://github.com/react-navigation/react-navigation/commit/bd09153448b7d9a3d62d7228020e6f1bd2bef74c

**Comment by raffjones** [comment]
@EvanBacon That does not solve it, unfortunately. The issue should not be closed.

**Comment by EvanBacon** [comment]
Unless you can provide a repro, this issue is solved. Running `expo start` in `/expo-managed-workflow` will start just fine. Adding `react-navigation` will also work. I cannot infer any more possible information from what you've provided.

**Comment by pelhage** [comment]
@raffjones @EvanBacon I'm also facing this issue, and adding `yarn add react-navigation@3.5.1` didn't solve it for me

I scaffolded out a new project with `expo init` and a managed workflow, then added `react-native-web` and `react-dom` plus `web` in `app.json` as the instructions stated

These are the types of errors I'm getting:
<img width="1048" alt="Screen Shot 2019-04-04 at 3 41 31 PM" src="https://user-images.githubusercontent.com/4411839/55593296-24242880-56f0-11e9-9717-0836562e3bd7.png">

<img width="830" alt="Screen Shot 2019-04-04 at 3 38 17 PM" src="https://user-images.githubusercontent.com/4411839/55593232-f212c680-56ef-11e9-9e74-417209db58ab.png">

Let me know if there's anything I can do to help out with this issue @EvanBacon

**Comment by raffjones** [comment]
@pelhage As @EvanBacon correctly said, everything works fine when you start by cloning the `web-examples` repo and setting up from the `/expo-managed-workflow` directory, but the instructions for starting from an `expo-init` app do not work. 

There is a repro for this as confirmed by @pelhage  - just follow the steps on [this page](https://github.com/expo/web-examples/blob/master/expo-managed-workflow/README.md) and it will not compile.

**Comment by pelhage** [comment]
I took a look at the `/expo-managed-workflow` project and saw it included 

`"expo": "^33.0.0-alpha.web.1"` in the `package.json`

`yarn add  expo@^33.0.0-alpha.web.1` fixed the issue for me, I can now compile to web @raffjones 

However, now `yarn android` doesn't work for me, throwing errors:

`The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable adn this code is not running on Expo`

**Comment by kay-is** [comment]
@pelhage installing the alpha version manually worked for me.

I ran

     npm show expo versions

to get a list with the latest version (which is 33.0.0-alpha.web.3 as I write) and installed it.

**Comment by wmcbain** [comment]
To reiterate a couple comments in here thank you @kay-is and @tibudiyanto

Remove any references of `@expo/samples` and replace any views/components from that package with a `View` from:

```
import { View } from 'react-native-web'
```

Then:

```
yarn add expo@33.0.0-alpha.web.3
```
