### ISSUE TITLE
Expo init example crashes on Android & iOS 

### ISSUE THREAD

**Issue by jaimebiernaski** [expo/web-examples#14]
Hi,

I'm facing 2 problems to run the example through expo  (v 2.13.0)

Following the described steps...

```
$ npm i -g expo-cli
$ expo init
$ yarn add react-native-web react-dom expo@next 
```
Add "web" to platforms in the app.json:
```
"platforms": [
    "android",
    "ios",
+    "web"
]
```
After starting...
```

$ expo start
```
The problems shows up:

1) Fist problem
```
Error: Problem validating fields in app.json. See https://docs.expo.io/versions/v32.0.0/workflow/configuration/
 • Field: platforms - should NOT have more than 2 items.

```
2) Second Problem: The Web works, but it crashes on Android...

![rnwExpoError](https://user-images.githubusercontent.com/31888408/55001069-98552280-4fb2-11e9-87d9-f6753dbf253a.png)

**Comment by nicolazj** [comment]
same problem here. it crashed on iOS.

**Comment by EvanBacon** [comment]
https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375
> it will not be until the next SDK version that Expo Web projects are compatible with managed Android and iOS projects since this web beta is not part of an official Expo SDK version.

**Comment by multimulti** [comment]
> https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375
> > it will not be until the next SDK version that Expo Web projects are compatible with managed Android and iOS projects since this web beta is not part of an official Expo SDK version.

Thanks for this insight, I also stumbled upon this. You don't by chance have an date/month estimate for when Web projects are compatible with managed Android/iOS projects? Cause that would be great!

Thanks for all you're doing here :-)

**Comment by lvmmth** [comment]
Same problem to me.
