### ISSUE TITLE
Possibility of SSR?

### ISSUE THREAD

**Issue by arrygoo** [expo/web-examples#18]
Is it possible to have SSR with Expo Web for better SEO?

**Comment by EvanBacon** [comment]
sure https://github.com/necolas/react-native-web/blob/master/docs/guides/server-side-rendering.md

**Comment by EAT-CODE-KITE-REPEAT** [comment]
Can anyone give an example of this with Expo? I don't really understand how to integrate this in my RN App

**Comment by EvanBacon** [comment]
https://docs.expo.io/versions/latest/guides/using-nextjs/

**Comment by zhirzh** [comment]
> sure [react native web SSR](https://github.com/necolas/react-native-web/blob/master/docs/guides/server-side-rendering.md)

resource moved to [here](https://github.com/necolas/react-native-web/blob/master/packages/docs/src/guides/server-side-rendering.stories.mdx)
