### ISSUE TITLE
How to use SVG on web?

### ISSUE THREAD

**Issue by AlexGrafe** [expo/web-examples#28]
The [features page](https://github.com/expo/web-examples/blob/master/docs/FEATURES.md) mentions `expo-svg` but the [link](https://github.com/expo/expo/tree/master/packages/expo-svg) is broken and `.../packages/expo-svg` doesn't exist anymore.

Could you tell me what to put in my `package.json` to use SVG on web?

Thanks!

**Comment by EvanBacon** [comment]
Sorry about that. You can use 

```jsx
import { Svg } from 'expo';
const { G, Circle } = Svg;
return (<G />)
```

**Comment by AlexGrafe** [comment]
Fantastic, thanks!
