### ISSUE TITLE
ReferenceError: Can't find variable: module

### ISSUE THREAD

**Issue by kations** [expo/web-examples#37]
Get the same error when I try to use apollo: 
https://github.com/apollographql/apollo-client/issues/4421

this seems to help =>

Could you try adding this to your webpack module rules:

       {
          test: /\.mjs$/,
          include: /node_modules/,
          type: 'javascript/auto',
        },

is it possible to add something to the web pack config?

**Comment by hew** [comment]
@kations https://github.com/expo/web-examples/blob/master/docs/WEBPACK.md

**Comment by EvanBacon** [comment]
https://docs.expo.io/versions/v33.0.0/guides/customizing-webpack/

**Comment by EvanBacon** [comment]
Related: https://github.com/expo/expo-cli/pull/731
