### ISSUE TITLE
Expo camera error for web

### ISSUE THREAD

**Issue by FrenchBully** [expo/web-examples#47]
Works natively on ios and android, however, I see a non-supported error thrown.  I thought the camera feature was fully supported on web according to: 
https://github.com/expo/web-examples/blob/master/docs/FEATURES.md

`let video = await this.camera.recordAsync();`

```
> 185 | async recordAsync(options?: RecordingOptions): Promise<{ uri: string }> {
      | ^  186 |   if (!CameraManager.record) {
  187 |     throw new UnavailabilityError('Camera', 'recordAsync');
  188 |   }
```

Error:
```
Unhandled Rejection (Error): The method or property Camera.recordAsync is not available on web, are you sure you've linked all the native dependencies properly?
```

**Comment by EvanBacon** [comment]
Recording video is not possible in the browser (in any meaningful way). This module is fully supported on web as far as what the web is capable of (AFAICT).

**Comment by sushrutha** [comment]
@EvanBacon I am facing the same issue. Trying to build a expo-web app to record daily standup from web. Any idea, why is recording video not possible in browser?

**Comment by mattpepin** [comment]
Not sure why it's not supported on the web. Videojs-record is an example of a working implementation:

https://github.com/collab-project/videojs-record
