### ISSUE TITLE
Expo web not working in production

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [expo/web-examples#50]
On development everything is fine, but in production it doesn't work. I've added a custom webpack config like this to build in dev mode, but this makes my app really slow and big. It even became too big for surge.sh

# webpack.config.js:
```
const expoConfig = require("@expo/webpack-config");
module.exports = function(env, argv) {
  // env.mode = "development"; // <-- turn this on to build in dev mode
  const config = expoConfig(env, argv);
  return config;
};
```

# Error:

`Uncaught TypeError: Cannot read property 'call' of undefined`

(Only shows up in production, not in development mode)

It may be related to https://github.com/webpack/webpack/issues/8996 but not sure!
Hope someone found a solution.

**Comment by EAT-CODE-KITE-REPEAT** [comment]
I just found some related issues:

https://github.com/expo/expo/issues/4545
https://github.com/expo/expo-cli/issues/843
https://github.com/expo/expo-cli/issues/843#issuecomment-511587188


May be fixed with those workarounds

**Comment by raphaelrk** [comment]
removeUnusedImportExports hasn't been working for me -- in the meanwhile I've just been using `expo build:web --dev`

**Comment by brookemitchell** [comment]
@EAT-CODE-KITE-REPEAT lil typo, change goes in `webpack.config.js` obviously
> After `expo customize:web`, This ~~babel.config~~ fixes it (Like @EvanBacon [suggested](https://github.com/expo/expo-cli/issues/843#issuecomment-511587188)):

**Comment by EvanBacon** [comment]
This is fixed now

**Comment by chayancbnits** [comment]
Sorry to say that I using SDK34, but I was written in webpack.config.js

const createExpoWebpackConfig = require('@expo/webpack-config');
const { getMode } = require('@expo/webpack-config/utils');

module.exports = async function (env, argv) {
  const mode = getMode(env);
  const isProd = mode === 'production';

  const config = await createExpoWebpackConfig(
    {
      ...env,
      removeUnusedImportExports: isProd,
    },
    argv);
  return config;
};


Still getting error


[=================== ] 95% (22.3 seconds)(node:15197) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at Hash.update (internal/crypto/hash.js:58:11)
    at exports.default (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/helpers/fingerprint.js:6:6)
    at processIcon (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/icons.js:44:29)
    at _callee3$ (/@expo/webpack-pwa-manifest-plugin@1.2.4/src/icons.js:137:10)
