### ISSUE TITLE
Error: Cannot find module 'eslint'

### ISSUE THREAD

**Issue by peeyush-sahu** [expo/web-examples#51]
I have tried expo web app following your instructions but it gives this error.

`
Trying to open the project in a web browser...
(node:3288) UnhandledPromiseRejectionWarning: Error: Cannot find module 'eslint'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at module.exports (/usr/local/lib/node_modules/expo-cli/node_modules/@expo/webpack-config/webpack/webpack.common.js:448:37)
(node:3288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 19)
(node:3288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

I have installed `eslint` it still gives me error.

**Comment by DanielFloris** [comment]
Same issue here

**Comment by DillonMemo** [comment]
Same issue here too

**Comment by cbanning510** [comment]
Same here.

Actions to recreate:

expo init (launch blank; name project)
yarn start
press 'w' to launch web

**Comment by FLGMwt** [comment]
This has been fixed as of expo-cli version 3.0.4. try updating to the latest expo-cli and give it another shot:

```
npm install --global expo-cli
```

**Comment by cbanning510** [comment]
fyi: I had to do the install using yarn:

yarn global add expo-cli

(likely an issue with my npm)
