### ISSUE TITLE
How to add homepage attribute in package.json?

### ISSUE THREAD

**Issue by loq24** [expo/web-examples#52]
I tried to add homepage attribute in package.json but it doesn't seem to work. I want deploy my app in a subdirectory. Thanks

**Comment by AlexGrafe** [comment]
Check out this issue about the `web.publicPath` which currently doesn't work anymore. It's to tell expo which subdirectory you're using for your app, e.g. `https://mydomain.com/myapp`.

#40

**Comment by EvanBacon** [comment]
Resolved https://github.com/expo/expo-cli/blob/69dc96d4790f0d35be145436c879f0c0e9f6964b/packages/webpack-config/src/env/paths.ts#L102-L129
