### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by peeyush-sahu** [expo/web-examples#53]
![image](https://user-images.githubusercontent.com/14846708/62104264-badaad80-b2bc-11e9-9139-28d367f9d002.png)

Expo Version: 3.0.6

Steps to reproduce:
1. Create project using expo-cli.
2. yarn add react-native-web react-dom
3. yarn add expo@next
4. expo start --web --non-interactive

**Comment by EvanBacon** [comment]
https://github.com/expo/expo/issues/5109
