### ISSUE TITLE
Deprecate this repo

### ISSUE THREAD

**Issue by EvanBacon** [expo/web-examples#62]
We should move all information to the expo docs via PRs into https://github.com/expo/expo 
And move all examples into https://github.com/expo/examples/

**Comment by nikznk** [comment]
Hi I would like to work on this one, just to clarify do you want to remove the files from https://github.com/expo/expo and add to the folder called examples in https://github.com/expo/examples/

**Comment by EvanBacon** [comment]
I think we should:
- Move the MD and guides from https://github.com/expo/web-examples/tree/master/docs into https://github.com/expo/expo/tree/master/docs/pages/versions/unversioned (it'll require more than a copy/paste)
- Add a CRA example (like this [CRA example](https://github.com/expo/web-examples/tree/master/create-react-app-example)) to the examples repo: https://github.com/expo/examples/

**Comment by nikznk** [comment]
hi thanks for the reply, can I just get some elaboration on the first point

**Comment by EvanBacon** [comment]
Notice how this file [PERFORMANCE.md](https://github.com/expo/web-examples/blob/master/docs/PERFORMANCE.md) is in the docs -> https://docs.expo.io/versions/v35.0.0/guides/web-performance/ here is the source: [web-performance](https://github.com/expo/expo/blob/master/docs/pages/versions/unversioned/guides/web-performance.md). We should move the other guides: CUSTOMIZING-STATICS.md, DEPLOYMENT.md, FEATURES.md, PWA.md, WEBPACK.md, adding-web-support-to-unimodules.md, developing.md as well. They'll need to be reworded a little bit to be less casual but that can be done in the PRs.
